version: '3.4'
services:
  redis:
    image: redis:5
    restart: unless-stopped
    volumes:
      - $PWD/docker/redis-data;/data
      - $PWD/docker/redis.conf:/usr/local/etc/redis/redis.conf
  manticore:
    image: manticoresearch/manticore:3
    restart: unless-stopped
    volumes:
      - $PWD/docker/manticore-data;/var/lib/manticore/data
      - $PWD/docker/sphinx.conf:/etc/sphinxsearch/sphinx.conf
  mariadb:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - $PWD/docker/my.cnf:/etc/mysql/conf.d/newsnab-tmux.cnf
      - $PWD/docker/mariadb-data:/var/lib/mysql
      - $PWD:/var/www/NNTmux/
    environment:
      MYSQL_ROOT_PASSWORD: ilmdvV8H
      MYSQL_DATABASE: nntmux
      MYSQL_USER: nntmux
      MYSQL_PASSWORD: Nntmux!
      TZ: ${APP_TZ}
  nn-tmux: &nn-tmux
    build:
      context: .
    restart: unless-stopped
    container_name: nn-tmux
    command: apachectl -D FOREGROUND
    volumes:
      - /var/www/NNTmux/vendor/
      - $PWD:/var/www/NNTmux/
    env_file: .env
    ports:
      - 127.0.0.1:8089:80
    environment:
      MYSQL_ROOT_PASSWORD: ilmdvV8H
      TZ: ${APP_TZ}
    depends_on:
      - mariadb
      - redis
      - manticore
  nn-tmux-ui:
    <<: *nn-tmux
    container_name: nn-tmux-ui
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ilmdvV8H
      TZ: ${APP_TZ}
      COLUMNS: "`tput cols`"
      LINES: "`tput lines`"
    command: sudo -E -u notroot php artisan tmux-ui:start
    ports:
      - 127.0.0.1:12345:12345